# Hi 👋, I'm  Himanshu Kumar

🎓 AIML Student

💻 Passionate about Machine Learning, Django, and DevOps

🔧 Skills:
- Python
- Django
- Machine Learning
- Git & GitHub
- GitHub Actions
- CI/CD
- Linux

🚀 Currently learning:
- MLOps
- Cloud Computing
- Advanced CI/CD Pipelines

📫 Connect with me:
- LinkedIn: https://linkedin.com/in/himanshux64
- GitHub: https://github.com/himanshux64
